server:
  port: 8050
eureka:
  instance:
    prefer-ip-address: true     #是否显示主机的Ip
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/     #指定eureka服务端地址
spring:
  application:
    name: springcloud-demo-zuul     #指定应用名称
zuul:
  routes:
    order-serverId:      #zuul的唯一标识
      path: /order/**       #需要映射的路径
      service-id: springcloud-demo-order